USE hoa;

INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (1, 1, 1000, 465, 8985, '00119-3026', 'SG000000119', 'SG000119H001', 'SG000119H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Alexander Koruth', '936-828-9073', '', '', '', '',
        '14838 Beaconsfield Dr', '', 'Dallas', 'Tx', '77043', null, '14838 Beaconsfield Dr', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '6', '13', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (2, 1, 1000, 465, 8985, '00120-9949', 'SG000001439', 'SG001439H001', 'SG001439H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Esther Garcia', '936-208-2542', '', '', '', '', '1419 Stevenage Lane',
        '', 'Dallas', 'Tx', '77043', null, '1419 Stevenage Lane', '', 'Dallas', 'Tx', '77043', 'Dallas', '7', '4',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (3, 1, 1000, 465, 8985, '00230-7608', 'SG000002215', 'SG002215H001', 'SG002215H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Luis Vasquez', '910-527-2419', '', '', '', '', '14830 Scotter Dr', '',
        'Dallas', 'Tx', '77043', null, '14830 Scotter Dr', '', 'Dallas', 'Tx', '77043', 'Dallas', '2', '15',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (4, 1, 1000, 465, 8985, '00121-2952', 'SG000001659', 'SG001659H001', 'SG001659H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Wade Chen', '901-505-0729', '', '', '', '', '1418 Willersley Lane', '',
        'Dallas', 'Tx', '77043', null, '1418 Willersley Lane', '', 'Dallas', 'Tx', '77043', 'Dallas', '4', '5',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (5, 1, 1000, 465, 8985, '00119-3589', 'SG000000168', 'SG000168H001', 'SG000168H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Thomas Zacharian', '845-480-1326', '', '845-627-1851', '', '',
        '15330 Bedford Glen Dr', '', 'Dallas', 'Tx', '77043', null, '15330 Bedford Glen Dr', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '6', '6', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (6, 1, 1000, 465, 8985, '00182-2449', 'SG000002020', 'SG002020H001', 'SG002020H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Erasmo Alas', '8362-231-3817', '', '214-452-0029', '', '',
        '14856 Peachmeadow Lane', '', 'Dallas', 'Tx', '77043', null, '14856 Peachmeadow Lane', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '4', '5', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (7, 1, 1000, 465, 8985, '00187-4620', 'SG000002056', 'SG002056H001', 'SG002056H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Ezequiel Quiroz', '831-594-9905', '', '', '', '', '14815 Welbeck Drive',
        '', 'Dallas', 'Tx', '77043', null, '14815 Welbeck Drive', '', 'Dallas', 'Tx', '77043', 'Dallas', '9', '15',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (8, 1, 1000, 465, 8985, '00120-0168', 'SG000000699', 'SG000699H001', 'SG000699H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Alex and Josh Mathers', '821-812-1104', '', '', '', '',
        '14814 Keelby Dr', '', 'Dallas', 'Tx', '77043', null, '14814 Keelby Dr', '', 'Dallas', 'Tx', '77043', 'Dallas',
        '8', '10', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (9, 1, 1000, 465, 8985, '00120-3644', 'SG000000975', 'SG000975H001', 'SG000975H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'James Thompson', '821-457-0003', '', '817-894-3343', '', '',
        '1418 Oakengates Dr', '', 'Dallas', 'Tx', '77043', null, '1418 Oakengates Dr', '', 'Dallas', 'Tx', '77043',
        'Dallas', '3', '11', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (10, 1, 1000, 465, 8985, '00187-3919', 'SG000002054', 'SG002054H001', 'SG002054H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Teresa Guevera', '817-998-9616', '', '', '', '', '14840 Welbeck Drive',
        '', 'Dallas', 'Tx', '77043', null, '14840 Welbeck Drive', '', 'Dallas', 'Tx', '77043', 'Dallas', '15', '12',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (11, 1, 1000, 465, 8985, '00120-7187', 'SG000001233', 'SG001233H001', 'SG001233H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Rogelio Nieto', '817-984-8918', '', '', '', '',
        '14910 S Silver Green Dr', '', 'Dallas', 'Tx', '77043', null, '14910 S Silver Green Dr', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '2', '14', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (12, 1, 1000, 465, 8985, '00119-8694', 'SG000000579', 'SG000579H001', 'SG000579H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Manuela Kinsale', '817-984-1224', '', '', '', '',
        '1354 Great Dover Cir', '', 'Dallas', 'Tx', '77043', null, '1354 Great Dover Cir', '', 'Dallas', 'Tx', '77043',
        'Dallas', '6', '8', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (13, 1, 1000, 465, 8985, '00145-6323', 'SG000001784', 'SG001784H001', 'SG001784H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'David Diaz', '817-984-1122', '', '762-922-3070', '', '',
        '15123 Peachmeadow Lane', '', 'Dallas', 'Tx', '77043', null, '15123 Peachmeadow Lane', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '12', '3', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (14, 1, 1000, 465, 8985, '00121-2279', 'SG000001602', 'SG001602H001', 'SG001602H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Erin Worley', '817-964-7996', '', '', '', '', '14850 Welbeck Drive', '',
        'Dallas', 'Tx', '77043', null, '14850 Welbeck Drive', '', 'Dallas', 'Tx', '77043', 'Dallas', '15', '10',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (15, 1, 1000, 465, 8985, '00121-3728', 'SG000001726', 'SG001726H001', 'SG001726H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Ruben L. Estrada', '817-947-8111', '', '', '', '', '1411 Wrotham Lane',
        '', 'Dallas', 'Tx', '77043', null, '1411 Wrotham Lane', '', 'Dallas', 'Tx', '77043', 'Dallas', '13', '6',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (16, 1, 1000, 465, 8985, '00148-4311', 'SG000001807', 'SG001807H001', 'SG001807H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Latoyna Gibson', '817-938-4357', '', '214-448-7550', '', '',
        '15046 Easingwold Dr', '', 'Dallas', 'Tx', '77043', null, '15046 Easingwold Dr', '', 'Dallas', 'Tx', '77043',
        'Dallas', '10', '1', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (17, 1, 1000, 465, 8985, '00121-3320', 'SG000001690', 'SG001690H001', 'SG001690H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Jomar C. White', '817-928-3277', '', '817-928-4024', '', '',
        '1315 Wrotham Lane', '', 'Dallas', 'Tx', '77043', null, '1315 Wrotham Lane', '', 'Dallas', 'Tx', '77043',
        'Dallas', '3', '15', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (18, 1, 1000, 465, 8985, '00153-9198', 'SG000001846', 'SG001846H001', 'SG001846H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Yasmin Davila', '817-918-8266', '', '', '', '', '1347 Stevenage Lane',
        '', 'Dallas', 'Tx', '77043', null, '1347 Stevenage Lane', '', 'Dallas', 'Tx', '77043', 'Dallas', '14', '14',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (19, 1, 1000, 465, 8985, '00202-1757', 'SG000002171', 'SG002171H001', 'SG002171H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Alfredo Centeno', '817-889-7291', '', '214-452-3230', '', '',
        '1310 Wrotham Lane', '', 'Dallas', 'Tx', '77043', null, '1310 Wrotham Lane', '', 'Dallas', 'Tx', '77043',
        'Dallas', '8', '6', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (20, 1, 1000, 465, 8985, '00120-1251', 'SG000000785', 'SG000785H001', 'SG000785H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Edy Garcia', '817-884-7656', '', '', '', '', '1346 Littleport Lane', '',
        'Dallas', 'Tx', '77043', null, '1346 Littleport Lane', '', 'Dallas', 'Tx', '77043', 'Dallas', '3', '6',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (21, 1, 1000, 465, 8985, '00175-0139', 'SG000001978', 'SG001978H001', 'SG001978H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Marcos Fuentes Jr', '817-883-6765', '', '762-626-3027', '', '',
        '14839 Peachmeadow Lane', '', 'Dallas', 'Tx', '77043', null, '14839 Peachmeadow Lane', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '9', '11', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (22, 1, 1000, 465, 8985, '00121-1526', 'SG000001565', 'SG001565H001', 'SG001565H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Antonio Ventura', '817-878-2479', '', '', '', '', '14923 Wainsfield Dr',
        '', 'Dallas', 'Tx', '77043', null, '14923 Wainsfield Dr', '', 'Dallas', 'Tx', '77043', 'Dallas', '13', '1',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (23, 1, 1000, 465, 8985, '00119-3534', 'SG000000163', 'SG000163H001', 'SG000163H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Arturo Torres', '817-877-2120', '', '409-998-1855', '', '',
        '15319 Bedford Glen Dr', '', 'Dallas', 'Tx', '77043', null, '15319 Bedford Glen Dr', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '9', '1', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (24, 1, 1000, 465, 8985, '00120-4601', 'SG000001030', 'SG001030H001', 'SG001030H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Gerald Lawrence', '817-875-5296', '', '214-840-9932', '', '',
        '15018 Peachmeadow Lane', '', 'Dallas', 'Tx', '77043', null, '15018 Peachmeadow Lane', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '9', '2', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (25, 1, 1000, 465, 8985, '00119-5448', 'SG000000318', 'SG000318H001', 'SG000318H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Charles Hudson', '817-869-7194', '', '', '', '', '1406 Crawley Ct', '',
        'Dallas', 'Tx', '77043', null, '1406 Crawley Ct', '', 'Dallas', 'Tx', '77043', 'Dallas', '15', '10',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (26, 1, 1000, 465, 8985, '00120-1840', 'SG000000829', 'SG000829H001', 'SG000829H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Tony Taft', '817-868-8506', '', '', '', '', '1302 Mac Clesby Lane', '',
        'Dallas', 'Tx', '77043', null, '1302 Mac Clesby Lane', '', 'Dallas', 'Tx', '77043', 'Dallas', '8', '11',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (27, 1, 1000, 465, 8985, '00120-2807', 'SG000000907', 'SG000907H001', 'SG000907H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Luis Duarte', '817-868-5995', '', '', '', '', '1714 Merton Dr', '',
        'Dallas', 'Tx', '77043', null, '1714 Merton Dr', '', 'Dallas', 'Tx', '77043', 'Dallas', '3', '4',
        'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (28, 1, 1000, 465, 8985, '00120-5215', 'SG000001075', 'SG001075H001', 'SG001075H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Billie J Fitzpatrick', '817-868-4628', '', '', '', '',
        '15250 Peachmeadow Lane', '', 'Dallas', 'Tx', '77043', null, '15250 Peachmeadow Lane', '', 'Dallas', 'Tx',
        '77043', 'Dallas', '1', '11', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (29, 1, 1000, 465, 8985, '00120-1950', 'SG000000836', 'SG000836H001', 'SG000836H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Sandra Escamilla', '817-868-2095', '', '', '', '',
        '1327 Mac Clesby Lane', '', 'Dallas', 'Tx', '77043', null, '1327 Mac Clesby Lane', '', 'Dallas', 'Tx', '77043',
        'Dallas', '4', '7', 'Silver Green CIA', '');
INSERT INTO `import`(`import_id`, `upload_id`, `import_status_id`, `association_id`, `company_id`,
                     `external_account_id`, `internal_account_id`, `internal_owner_id`, `internal_property_id`, `un`,
                     `pw`, `ownership_start_date`, `created_at`, `name_first`, `name_middle`, `name_last`,
                     `name_suffix`, `name_formal`, `phone_home`, `phone_mobile`, `phone_work`, `phone_fax`, `email`,
                     `mailing_address_line1`, `mailing_address_line2`, `mailing_address_city`, `mailing_address_state`,
                     `mailing_address_zip_code`, `mailing_address_country`, `property_address_line1`,
                     `property_address_line2`, `property_address_city`, `property_address_state`,
                     `property_address_zip_code`, `county`, `lot`, `block`, `subdivision`, `legal_description`)
VALUES (30, 1, 1000, 465, 8985, '00173-2775', 'SG000001969', 'SG001969H001', 'SG001969H001', '', '', '2012-01-05',
        '2019-09-13 19:55:23', '', '', '', '', 'Abel Gonzalez', '817-867-4699', '', '', '', '', '1442 Littleport Lane',
        '', 'Dallas', 'Tx', '77043', null, '1442 Littleport Lane', '', 'Dallas', 'Tx', '77043', 'Dallas', '2', '5',
        'Silver Green CIA', '');
