USE information_schema;


SELECT ORDINAL_POSITION
     , TABLE_SCHEMA
     , TABLE_NAME
     , COLUMN_NAME
     , COLUMN_DEFAULT
     , IS_NULLABLE
     , DATA_TYPE
     , COLUMN_COMMENT
--
-- , TABLE_CATALOG
-- ,TABLE_SCHEMA
-- ,TABLE_NAME
-- ,COLUMN_NAME
-- ,CHARACTER_MAXIMUM_LENGTH
-- ,CHARACTER_OCTET_LENGTH
-- ,NUMERIC_PRECISION
-- ,NUMERIC_SCALE
-- ,DATETIME_PRECISION
-- ,CHARACTER_SET_NAME
-- ,COLLATION_NAME
-- ,COLUMN_TYPE
-- ,COLUMN_KEY
-- ,EXTRA
-- ,PRIVILEGES
--
-- ,IS_GENERATED
-- ,GENERATION_EXPRESSION
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'hoa'
ORDER BY TABLE_NAME
       , ORDINAL_POSITION;